apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
spec:
  selector:
    app: mysqlPod
  type: ClusterIP
  #clusterIP: 10.99.15.15
  ports:
      - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mysql
spec:
  template:
    metadata:
      name: pod-mysql
      labels:
        app: mysqlPod
        type: mysqltype
    spec:
      containers:
        - name: containermysql
          image: image_mysql
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          volumeMounts: # папка внутри линукса
            - mountPath: "/var/lib/mysql"
              name: mysql
          #livenessProbe:
          #  exec:
          #    command:
          #      - sh
          #      - /check.sh
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
      volumes:  #внутри minikube папка
        - name: mysql
          hostPath:
            path: /mnt/mysql
            type: Directory
  replicas: 1
  selector:
    matchLabels:
      app: mysqlPod
      type: mysqltype
