apiVersion: v1
kind: Service
metadata:
  name: svc-phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  #loadBalancerIP: 192.168.99.116
  ports:
  - name: port-phpmyadmin
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: phpmyadminPod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-phpmyadmin
spec:
  template:
    metadata:
      name: pod-phpmyadmin
      labels:
        app: phpmyadminPod
        type: phpmyadmintype
    spec:
      containers:
        - name: phpmyadmincontainer
          image: image_phpmyadmin
          imagePullPolicy: Never
          ports:
            - name: phpmyadmin
              containerPort: 5000
          livenessProbe:
            exec:
              command:
                - sh
                - /checker.sh
            initialDelaySeconds: 30
            periodSeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadminPod
      type: phpmyadmintype
