apiVersion: v1
kind: Service
metadata:
  name: svc-wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpressPod
  type: LoadBalancer
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-wordpress
spec:
  template:
    metadata:
      name: pod-wordpress
      labels:
        app: wordpressPod
        type: wordpresstype
    spec:
      containers:
        - name: container-wordpress
          image: image_wordpress
          imagePullPolicy: Never
          ports:
            - name: wordpress
              containerPort: 5050
          livenessProbe:
            exec:
              command:
                - sh
                - /checker.sh
            initialDelaySeconds: 30
            periodSeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: wordpressPod
      type: wordpresstype
